### ISSUE TITLE
Create an Urban Gardening Community

### ISSUE THREAD

**Issue by Jayesh-JainX** [Jayesh-JainX/Hacktoberfest--23#36]
### Description:
We're promoting urban gardening. Your task is to design a community platform for urban gardeners with a green and eco-friendly design.

* Difficulty: beginner
* Estimated Time: 4-5 hours

**Comment by abc00xyz** [comment]
### Hello User,
Thank you for your interest in working on this issue. I've assigned the issue to you, and you can now start working on it. If you have any questions or need any assistance, feel free to ask. Good luck with your contribution!

Best regards,
[Jayesh](https://github.com/Jayesh-jainx)

**Comment by Jayesh-JainX** [comment]
### Hello User,
Thank you for your interest in working on this issue. I've assigned the issue to you, and you can now start working on it. If you have any questions or need any assistance, feel free to ask. Good luck with your contribution!

Best regards,
[Jayesh](https://github.com/Jayesh-jainx)
